--- 
schema: 
  format: 
    openapi: "3.0.0"
  service_input_type: K8sInput
  types: 
    K8sInput: 
      type: object
      description: "Input properties for K8s Objects"
      properties: 
        aws_region: 
          default: "us-west-2"
          description: "This is your EKS aws region"
          type: string
        cluster_id: 
          default: "proton-demo"
          description: "This is k8s cluster id"
          type: string
        namespace_name: 
          description: "This is k8s namspace for micro service"
          type: string
