--- 
schema: 
  service_input_type: "K8sInput"
   pipeline_input_type: "PipelineInputs" 
  format: 
    openapi: "3.0.0"
  types: 
    K8sInput: 
      type: object
      description: "Input properties for K8s Objects"
      properties: 
        aws_region: 
          default: us-east-2
          description: "This is your EKS aws region"
          type: string
        cluster_id: 
          default: eksworkshop-eksctl
          description: "This is k8s cluster id"
          type: string
        namespace_name: 
          description: "This is k8s namspace for micro service"
          type: string
      PipelineInputs:
      type: object
      description: "Pipeline input properties"
      properties:
        service_dir:
          type: string
          description: "Source directory for the service"
          default: ""
          minLength: 1
          maxLength: 100