--- 
schema: 
  environment_input_type: K8sInput
  format: 
    openapi: "3.0.0"
  types: 
    K8sInput: 
      description: "Input properties for K8s Objects"
      properties: 
        aws_region: 
          default: us-east-2
          description: "This is your EKS aws region"
          type: string
        cluster_id: 
          default: eksworkshop-eksctl
          description: "This is k8s cluster id"
          type: string
        namespace_name: 
          description: "This is k8s namspace for micro service"
          type: string
      type: object
