schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "K8sInput"
  types:
    K8sInput:
      type: object
      description: "Input properties for K8s Objects"
      properties:
        aws_region:
          type: string
          description: "This is your EKS aws region"
          default: "us-east-2"
       namespace_name:
          type: string
          description: "This is k8s namspace for micro service"
        cluster_id:
          type: string
          description: "This is k8s cluster id"
          default: "eksworkshop-eksctl"