schema: 
  format: 
    openapi: "3.0.0"
  service_input_type: "Ec2Input"
  types: 
    Ec2Input: 
      type: object
      description: "Input properties for K8s Objects"
      properties:
        instance_type:
          description: "This is instance_type for your ec2 instance"
          type: string
        ami:
          description: "This is ami for your ec2 instance"
          type: string